version: '3.8'

services:
  rr_ito_db:
    image: mysql:latest
    container_name: rr_ito_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ${DB_DATA_PATH}:/var/lib/mysql
    networks:
      - rr_ito_network

  rr_ito_web:
    build: .
    container_name: rr_ito_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - rr_ito_db
    networks:
      - rr_ito_network

networks:
  rr_ito_network:
    driver: bridge